name: corona_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  get_it: ^3.1.0
  scoped_model: ^1.0.1
  transparent_image: ^1.0.0
  webview_flutter: ^0.3.19+9
  flutter_local_notifications: ^1.3.0
  bottom_navy_bar: ^5.3.2
  carousel_pro: ^1.0.0
  carousel_slider: ^1.3.0
  cloud_firestore: ^0.13.4+2
  firebase_dynamic_links: ^0.5.0+11
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+3

  firebase_analytics: ^2.1.1+3
  # rxdart: ^0.23.1
  rxdart: ^0.21.0
  geolocator: ^3.0.1


  # cloud_firestore: ^0.9.13+1

  firebase_auth: 
  google_sign_in: 

  google_fonts: ^0.3.10
  store_redirect: ^1.0.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - veg.png
   - handwash.png
   - citricfruit.png
   - drinkwater.png
   - placeholder.png
   - whologo.jpg
   - setu.png
   - whotwitter.png
   - mohfwtwitter.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    # fonts:
    #   - family:  MyFlutterApp
    #       fonts:
    #        - asset: fonts/MyFlutterApp.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
